// Easy to expand: add another object to MOVIES or TV_EPISODES.
const MOVIES=[
 {id:'m01',title:'National Lampoon’s Christmas Vacation',year:1989,runtime:'1h 37m',category:'Comedy',tier:'core'},
 {id:'m02',title:'The Family Stone',year:2005,runtime:'1h 43m',category:'Dramedy',tier:'core'},
 {id:'m03',title:'Just Friends',year:2005,runtime:'1h 36m',category:'Comedy',tier:'core'},
 {id:'m04',title:'Bad Santa',year:2003,runtime:'1h 32m',category:'Adult Comedy',tier:'core',naughty:true},
 {id:'m05',title:'Scrooged',year:1988,runtime:'1h 41m',category:'Comedy',tier:'core'},
 {id:'m06',title:'Home Alone',year:1990,runtime:'1h 43m',category:'Family Comedy',tier:'core'},
 {id:'m07',title:'Home Alone 2: Lost in New York',year:1992,runtime:'2h',category:'Family Comedy',tier:'core'},
 {id:'m08',title:'Elf',year:2003,runtime:'1h 37m',category:'Comedy',tier:'core'},
 {id:'m09',title:'Die Hard',year:1988,runtime:'2h 12m',category:'Action',tier:'core'},
 {id:'m10',title:'Lethal Weapon',year:1987,runtime:'1h 50m',category:'Action',tier:'extended'},
 {id:'m11',title:'Violent Night',year:2022,runtime:'1h 52m',category:'Action / Dark Comedy',tier:'core',naughty:true},
 {id:'m12',title:'Krampus',year:2015,runtime:'1h 38m',category:'Horror',tier:'core',naughty:true},
 {id:'m13',title:'Batman Returns',year:1992,runtime:'2h 6m',category:'Christmas Adjacent',tier:'wildcard'},
 {id:'m14',title:'Eyes Wide Shut',year:1999,runtime:'2h 39m',category:'Christmas Adjacent',tier:'wildcard'},
 {id:'m15',title:'A Christmas Story',year:1983,runtime:'1h 33m',category:'Classic Comedy',tier:'core'},
 {id:'m16',title:'It’s a Wonderful Life',year:1946,runtime:'2h 10m',category:'Classic',tier:'core'},
 {id:'m17',title:'Miracle on 34th Street',year:1947,runtime:'1h 36m',category:'Classic',tier:'core'},
 {id:'m18',title:'White Christmas',year:1954,runtime:'2h',category:'Classic / Musical',tier:'core'},
 {id:'m19',title:'The Night Before',year:2015,runtime:'1h 41m',category:'Adult Comedy',tier:'core',naughty:true},
 {id:'m20',title:'Office Christmas Party',year:2016,runtime:'1h 45m',category:'Adult Comedy',tier:'core',naughty:true},
 {id:'m21',title:'Gremlins',year:1984,runtime:'1h 46m',category:'Dark Comedy / Horror',tier:'extended',naughty:true},
 {id:'m22',title:'Black Christmas',year:1974,runtime:'1h 38m',category:'Horror',tier:'extended',naughty:true},
 {id:'m23',title:'Klaus',year:2019,runtime:'1h 36m',category:'Animation',tier:'core'},
 {id:'m24',title:'The Muppet Christmas Carol',year:1992,runtime:'1h 25m',category:'Family / Musical',tier:'core'},
 {id:'m25',title:'The Polar Express',year:2004,runtime:'1h 40m',category:'Animation',tier:'core'},
 {id:'m26',title:'Four Christmases',year:2008,runtime:'1h 28m',category:'Comedy',tier:'core'},
 {id:'m27',title:'Love Actually',year:2003,runtime:'2h 15m',category:'Romance / Comedy',tier:'core'},
 {id:'m28',title:'The Holiday',year:2006,runtime:'2h 16m',category:'Romance / Comedy',tier:'core'},
 {id:'m29',title:'Jingle All the Way',year:1996,runtime:'1h 29m',category:'90s Comedy',tier:'core'},
 {id:'m30',title:'A Very Harold & Kumar Christmas',year:2011,runtime:'1h 30m',category:'Adult Comedy',tier:'extended',naughty:true}
];
const TV_EPISODES=[
 {id:'t01',show:'The Office',title:'Christmas Party',season:2,episode:10,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t02',show:'The Office',title:'A Benihana Christmas, Part 1',season:3,episode:10,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t03',show:'The Office',title:'A Benihana Christmas, Part 2',season:3,episode:11,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t04',show:'The Office',title:'Moroccan Christmas',season:5,episode:11,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t05',show:'The Office',title:'Secret Santa',season:6,episode:13,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t06',show:'The Office',title:'Dwight Christmas',season:9,episode:9,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t07',show:'Community',title:'Abed’s Uncontrollable Christmas',season:2,episode:11,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t08',show:'Community',title:'Regional Holiday Music',season:3,episode:10,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t09',show:'Friends',title:'The One with the Holiday Armadillo',season:7,episode:10,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t10',show:'It’s Always Sunny in Philadelphia',title:'A Very Sunny Christmas',season:6,episode:13,runtime:'~43m',category:'Adult Comedy',tier:'core',naughty:true},
 {id:'t11',show:'Ted Lasso',title:'Carol of the Bells',season:2,episode:4,runtime:'~30m',category:'Comedy / Drama',tier:'core'},
 {id:'t12',show:'Brooklyn Nine-Nine',title:'Christmas',season:1,episode:11,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t13',show:'Parks and Recreation',title:'Christmas Scandal',season:2,episode:12,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t14',show:'Arrested Development',title:'Afternoon Delight',season:2,episode:6,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t15',show:'Frasier',title:'Merry Christmas, Mrs. Moskowitz',season:6,episode:10,runtime:'~22m',category:'Comedy',tier:'core'},
 {id:'t16',show:'Futurama',title:'Xmas Story',season:2,episode:4,runtime:'~22m',category:'Animation',tier:'extended'},
 {id:'t17',show:'American Dad!',title:'Rapture’s Delight',season:5,episode:9,runtime:'~22m',category:'Adult Animation',tier:'extended',naughty:true},
 {id:'t18',show:'Family Guy',title:'Road to the North Pole',season:9,episode:7,runtime:'~44m',category:'Adult Animation',tier:'extended',naughty:true},
 {id:'t19',show:'Seinfeld',title:'The Strike',season:9,episode:10,runtime:'~22m',category:'Festivus / Comedy',tier:'extended'},
 {id:'t20',show:'Modern Family',title:'Undeck the Halls',season:1,episode:10,runtime:'~22m',category:'Comedy',tier:'core'}
];
